version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-Inventory
    environment:
      MYSQL_ROOT_PASSWORD: redhat
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql